language: go
go:
  - "1.10"
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
install:
    - go get github.com/user/bisrepo/mymodule
script: if [ "${BUILD_GOOS}" == "linux" ]; then GOARCH=${BUILD_GOARCH} GOOS=${BUILD_GOOS} make test; fi;
before_deploy:
  - GOARCH=${BUILD_GOARCH} GOOS=${BUILD_GOOS} go build -ldflags "-X main.version=${TRAVIS_TAG}" -o build/mocker cmd/mocker/main.go
  - tar -C build -cvzf mocker-${TRAVIS_TAG}-${BUILD_GOOS}.tar.gz .
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "mocker-${TRAVIS_TAG}-${BUILD_GOOS}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
